name: Deployment Status

on:
  push:
    branches:
      - main

jobs:
  pre-deployment:
    name: pre-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: echo "Hello World"
